services:
  web:
    build:
      context: ./src/web
      dockerfile: Dockerfile
    container_name: web_server
    ports:
      - "5000:5000"
    networks:
      - app_network
    restart: always

  server:
    build:
      context: ./src/server
      dockerfile: Dockerfile
    container_name: audio_server
    ports:
      - "8000:8000"
    networks:
      - app_network
    restart: always

networks:
  app_network:
    driver: bridge